### PR TITLE
Use overflow-wrap: anywhere; instead of overflow-wrap: break-word;

### PR DESCRIPTION
**Pull request by tamanyan**
## Summary

Replace all `overflow-wrap: break-word;` with `overflow-wrap: anywhere;`

## Related Issues

- #143

### CODE REVIEW

**Comment by tamanyan** [comment]
@tushuhei I would appreciate it if you could review my PR.

**Comment by tushuhei** [comment]
@tamanyan Thanks for this PR!
@kojiishi May I ask what you think of this change?

**Comment by kojiishi** [comment]
LGTM, this looks like a reasonable change to me.

**Review by kojiishi — APPROVED** [review]

**Comment by tamanyan** [comment]
@tushuhei @kojiishi Thank you both!!

**Pull request merged**
