### PR TITLE
Add custom help formatter and shorthand of `--thres`

### PR DESCRIPTION
**Pull request by eggplants**
```shellsession
$ budoux -h
usage: budoux [-h] [-H] [-m JSON] [-d STR] [-t THRES] [-V] [TXT]

BudouX is the successor to Budou,
the machine learning powered line break organizer tool.

positional arguments:
  TXT                      text (default: None)

optional arguments:
  -h, --help               show this help message and exit
  -H, --html               HTML mode (default: False)
  -m JSON, --model JSON    custom model file path (default: /Users/eggplants/prog/budoux/budoux/models/ja-knbc.json)
  -d STR, --delim STR      output delimiter in TEXT mode (default: ---)
  -t THRES, --thres THRES  threshold value to separate chunks (default: 1000)
  -V, --version            show program's version number and exit

```

### CODE REVIEW

**Comment by eggplants** [comment]
Would it be better to write a reference to CLI in the README? (As well `javascript/README.md`)

**Comment by tushuhei** [comment]
The change LGTM! Thank you so much.

> Would it be better to write a reference to CLI in the README? (As well javascript/README.md)

That would be awesome. Are you interested in writing the draft?

**Comment by eggplants** [comment]
@tushuhei @junseinagao could you port this over to Javascript?

**Comment by junseinagao** [comment]
@eggplants 

I'll implement this function to node cli. Give me a few days!

**Pull request merged**
