### PR TITLE
Unittest CI for Python

### PR DESCRIPTION
**Pull request by eggplants**
I have added unittesting CI for Python.

Note: *This project apparently works in Python 3.9 due to typing annotation (like: `list[str]`), so we have to restrict `python_requires` in `setup.cfg`!*

https://github.com/eggplants/budoux/blob/1c5ce47e260e38abece8c1b26ac8af00b1e6541b/setup.cfg#L21

### CODE REVIEW

**Comment by eggplants** [comment]
See: 
https://github.com/eggplants/budoux/actions/runs/1497575759

image

**Comment by eggplants** [comment]
Now this project works well with 3.9 only.
https://github.com/eggplants/budoux/actions/runs/1497688646
image

**Comment by eggplants** [comment]
Now this project works well with 3.9, 3.10 only.
https://github.com/eggplants/budoux/actions/runs/1497708321
image

**Comment by tushuhei** [comment]
Thanks for pointing this out! I've pushed a change to fix the problematic type hints at a0eef65575d0da81fb6fcd79c980498ad61cce24.
Could you pull that change and see if it passes the tests?

**Comment by eggplants** [comment]
It works well except 3.6 because of `_io.TextIOWrapper.reconfigure`. It is not implemented in 3.6 or older. 


https://github.com/eggplants/budoux/runs/4308064338?check_suite_focus=true
image

**Comment by tushuhei** [comment]
Thank you for checking. Could you separate the changes around standard streams and text encodings to another PR? Then we can focus on the unit test CI for this PR.

**Pull request closed without merging**
